version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lets_hang_out
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  go-backend:
    build: ./go-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=lets_hang_out
      - PORT=8080
    depends_on:
      - mysql
    networks:
      - app-network

  react-app:
    build: ./react-app
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - go-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: