name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Minikube Docker Environment
      run: eval $(minikube docker-env)

    - name: Build Docker images locally
      run: |
        docker build -t react-app:latest ./react-app
        docker build -t go-backend:latest ./go-backend

    - name: Deploy to Minikube
      run: |
        kubectl apply -f react-deployment.yaml
        kubectl apply -f go-deployment.yaml

    - name: Check Deployment Status
      run: |
        kubectl get pods
        kubectl get services

